# Generated by Django 3.1 on 2020-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateOfTMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_uf', models.IntegerField(blank=True, default=500, null=True)),
                ('payment_deadline_days', models.IntegerField(blank=True, default=5, max_length=2, null=True)),
                ('payment_day_with_calculated_tmc', models.IntegerField(blank=True, default=6, max_length=2, null=True)),
                ('valor_tmc_at_day', models.IntegerField(blank=True, default=6, max_length=2, null=True)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('valor', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=300)),
            ],
        ),
    ]
