# Generated by Django 3.1 on 2020-08-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateoftmc',
            name='payment_day_with_calculated_tmc',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='rateoftmc',
            name='payment_deadline_days',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='rateoftmc',
            name='valor_tmc_at_day',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
