# Generated by Django 3.1 on 2020-08-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200816_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmc',
            name='fecha',
            field=models.CharField(default='', max_length=300),
        ),
    ]
